### model
model_name_or_path: /data/models/gemma-3-12b-it
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 256
lora_target: all
lora_dropout: 0.001
adapter_name_or_path: /data/Iman/LLM/models/gemma-3-12b-it-fawiki/checkpoint-150000
create_new_adapter: false
freeze_vision_tower: false
deepspeed: examples/deepspeed/ds_z0_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: QA_politics, GQA_non_politics, GQA_politics, title_non_politics, title_politics
template: gemma3
cutoff_len: 4096
max_length: 4096
overwrite_cache: true
preprocessing_num_workers: 128
dataloader_num_workers: 128

### output
output_dir: /data/Iman/lora_models/gemma12-fawiki-sft-persian
logging_steps: 10
save_strategy: steps
save_steps: 40000
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.0005
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 4000
