### model
model_name_or_path: /data/models/gemma-3-12b-it
trust_remote_code: true

### method
stage: pt
template: default
do_train: true
finetuning_type: lora
lora_rank: 256
lora_target: all
lora_dropout: 0.001
freeze_vision_tower: true
deepspeed: examples/deepspeed/ds_z0_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: wiki-en, fawiki2, wiki-arz, fawiki3, wiki-ar, fawiki1, wiki-zh
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data/Iman/LLM/models/gemma-3-12b-it-fawiki
logging_steps: 10
save_strategy: steps
save_steps: 30000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

#seeds
seed: 111
data_seed: 111

### eval
# val_size: 0.001
# per_device_eval_batch_size: 8
# eval_strategy: steps
# eval_steps: 200
