### model
model_name_or_path: /data/models/Llama-3.1-70B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: dolphin_translated
template: llama3
cutoff_len: 4096
max_length: 4096
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: /data/Iman/LLM/models/Llama3.1-70B_dolphin_translated_v2
logging_steps: 5
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
seed: 100
data_seed: 100

## eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

# mlflow
run_name: r1_sft_2
report_to: mlflow